apiVersion: cloudcost.datadog.m.upbound.io/v1alpha1
kind: AWSCURConfig
metadata:
  annotations:
    meta.upbound.io/example-id: cloudcost/v1alpha1/awscurconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    accountFilters:
    - excludedAccounts:
      - "123456789123"
      - "123456789143"
      includeNewAccounts: true
    accountId: "123456789123"
    bucketName: dd-cost-bucket
    bucketRegion: us-east-1
    reportName: dd-report-name
    reportPrefix: dd-report-prefix
