apiVersion: integration.upbound.io/v1alpha1
kind: AwsExternalID
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/awsexternalid
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider: {}

---

apiVersion: integration.upbound.io/v1alpha1
kind: AwsAccount
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/awsexternalid
  labels:
    testing.upbound.io/example-name: foo-defaults
  name: foo-defaults
spec:
  forProvider:
    authConfig:
    - awsAuthConfigRole:
      - externalId: ${datadog_integration_aws_external_id.foo.id}
        roleName: DatadogIntegrationRole
    awsAccountId: "123456789019"
    awsPartition: aws
