apiVersion: datadog.upbound.io/v1alpha1
kind: RestrictionPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/restrictionpolicy
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    bindings:
    - principals:
      - user:${data.datadog_current_user.me.id}
      relation: editor
    - principals:
      - org:${data.datadog_current_user.me.org_id}
      relation: viewer
    resourceId: security-rule:abc-def-ghi
