apiVersion: integration.datadog.upbound.io/v1alpha1
kind: FastlyService
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/fastlyservice
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: fastlyservice-foo
    serviceId: my-service-id
    tags:
    - mytag
    - mytag2:myvalue

---

apiVersion: integration.datadog.upbound.io/v1alpha1
kind: FastlyAccount
metadata:
  annotations:
    meta.upbound.io/example-id: integration.datadog/v1alpha1/fastlyservice
  labels:
    testing.upbound.io/example-name: fastlyservice-foo
  name: fastlyservice-foo
spec:
  forProvider:
    apiKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: fastlyservice-test-name
