apiVersion: datadog.m.upbound.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/role
  labels:
    testing.upbound.io/example-name: api_key_manager
  name: api-key-manager
  namespace: crossplane-system
spec:
  forProvider:
    name: API Key Manager
