apiVersion: datadog.m.upbound.io/v1alpha1
kind: ServiceAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/serviceaccesstoken
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    name: Monitor Management Service Access Token
    # Scopes are permission names, not permission ids.
    scopes:
    - api_keys_read
    serviceAccountId: ${data.datadog_service_account.uptest.id}
