apiVersion: datadog.m.upbound.io/v1alpha1
kind: ServiceAccountApplicationKey
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/serviceaccountapplicationkey
    upjet.upbound.io/manual-intervention: Requires the id of an existing service account; see serviceaccount.yaml.
  labels:
    testing.upbound.io/example-name: unrestricted_key
  name: unrestricted-key
  namespace: upbound-system
spec:
  forProvider:
    name: Unrestricted Service Account Key
    serviceAccountId: 00000000-0000-1234-0000-000000000000
