apiVersion: datadog.m.upbound.io/v1alpha1
kind: Team
metadata:
  name: team-foo
  namespace: crossplane-system
spec:
  forProvider:
    name: team-foo
    description: Team Foo
    handle: team-foo-handle
