apiVersion: datadog.m.upbound.io/v1alpha1
kind: TeamLink
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teamlink
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    label: Link label
    position: 0
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: teamlink-foo
    url: https://example.com

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teamlink
  labels:
    testing.upbound.io/example-name: teamlink-foo
  name: teamlink-foo
  namespace: upbound-system
spec:
  forProvider:
    description: Example team
    handle: teamlink-foo
    name: teamlink-foo
