apiVersion: on.upbound.io/v1alpha1
kind: CallSchedule
metadata:
  annotations:
    meta.upbound.io/example-id: on/v1alpha1/callschedule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    layer:
    - effectiveDate: "2025-01-01T00:00:00Z"
      endDate: "2026-01-01T00:00:00Z"
      interval:
      - days: 1
        seconds: 300
      name: Primary On-Call Layer
      restriction:
      - endDay: monday
        endTime: "17:00:00"
        startDay: monday
        startTime: "09:00:00"
      rotationStart: "2025-01-01T00:00:00Z"
      users:
      - 00000000-aba1-0000-0000-000000000000
    - effectiveDate: "2025-01-01T00:00:00Z"
      interval:
      - days: 7
      name: Asia-Pacific On-Call Layer
      rotationStart: "2025-01-01T00:00:00Z"
      timeZone: Asia/Tokyo
      users:
      - 00000000-aba1-0000-0000-000000000001
    name: Team A On-Call
    teams:
    - 00000000-aba2-0000-0000-000000000000
    timeZone: America/New_York
