/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DomainAllowlistInitParameters struct {

	// (List of String) The domains within the domain allowlist.
	// The domains within the domain allowlist.
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// (Boolean) Whether the Email Domain Allowlist is enabled.
	// Whether the Email Domain Allowlist is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type DomainAllowlistObservation struct {

	// (List of String) The domains within the domain allowlist.
	// The domains within the domain allowlist.
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// (Boolean) Whether the Email Domain Allowlist is enabled.
	// Whether the Email Domain Allowlist is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DomainAllowlistParameters struct {

	// (List of String) The domains within the domain allowlist.
	// The domains within the domain allowlist.
	// +kubebuilder:validation:Optional
	Domains []*string `json:"domains,omitempty" tf:"domains,omitempty"`

	// (Boolean) Whether the Email Domain Allowlist is enabled.
	// Whether the Email Domain Allowlist is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

// DomainAllowlistSpec defines the desired state of DomainAllowlist
type DomainAllowlistSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DomainAllowlistParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DomainAllowlistInitParameters `json:"initProvider,omitempty"`
}

// DomainAllowlistStatus defines the observed state of DomainAllowlist.
type DomainAllowlistStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DomainAllowlistObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DomainAllowlist is the Schema for the DomainAllowlists API. Provides the Datadog Email Domain Allowlist resource. This can be used to manage the Datadog Email Domain Allowlist.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type DomainAllowlist struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domains) || (has(self.initProvider) && has(self.initProvider.domains))",message="spec.forProvider.domains is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   DomainAllowlistSpec   `json:"spec"`
	Status DomainAllowlistStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DomainAllowlistList contains a list of DomainAllowlists
type DomainAllowlistList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DomainAllowlist `json:"items"`
}

// Repository type metadata.
var (
	DomainAllowlist_Kind             = "DomainAllowlist"
	DomainAllowlist_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DomainAllowlist_Kind}.String()
	DomainAllowlist_KindAPIVersion   = DomainAllowlist_Kind + "." + CRDGroupVersion.String()
	DomainAllowlist_GroupVersionKind = CRDGroupVersion.WithKind(DomainAllowlist_Kind)
)

func init() {
	SchemeBuilder.Register(&DomainAllowlist{}, &DomainAllowlistList{})
}
