/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrgGroupInitParameters struct {

	// (String) The name of the org group. String length must be at least 1.
	// The name of the org group. String length must be at least 1.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrgGroupObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the org group. String length must be at least 1.
	// The name of the org group. String length must be at least 1.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The site of the organization that owns this org group.
	// The site of the organization that owns this org group.
	OwnerOrgSite *string `json:"ownerOrgSite,omitempty" tf:"owner_org_site,omitempty"`

	// (String) The UUID of the organization that owns this org group.
	// The UUID of the organization that owns this org group.
	OwnerOrgUUID *string `json:"ownerOrgUuid,omitempty" tf:"owner_org_uuid,omitempty"`
}

type OrgGroupParameters struct {

	// (String) The name of the org group. String length must be at least 1.
	// The name of the org group. String length must be at least 1.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OrgGroupSpec defines the desired state of OrgGroup
type OrgGroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrgGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrgGroupInitParameters `json:"initProvider,omitempty"`
}

// OrgGroupStatus defines the observed state of OrgGroup.
type OrgGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrgGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrgGroup is the Schema for the OrgGroups API. Provides a Datadog Org Group resource. This can be used to create and manage Datadog organization groups.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type OrgGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrgGroupSpec   `json:"spec"`
	Status OrgGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrgGroupList contains a list of OrgGroups
type OrgGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrgGroup `json:"items"`
}

// Repository type metadata.
var (
	OrgGroup_Kind             = "OrgGroup"
	OrgGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrgGroup_Kind}.String()
	OrgGroup_KindAPIVersion   = OrgGroup_Kind + "." + CRDGroupVersion.String()
	OrgGroup_GroupVersionKind = CRDGroupVersion.WithKind(OrgGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&OrgGroup{}, &OrgGroupList{})
}
