/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrgGroupPolicyOverrideInitParameters struct {

	// (String) The UUID of the org group that owns the policy. Must be a valid UUID.
	// The UUID of the org group that owns the policy. Must be a valid UUID.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.OrgGroup
	OrgGroupID *string `json:"orgGroupId,omitempty" tf:"org_group_id,omitempty"`

	// Reference to a OrgGroup in datadog to populate orgGroupId.
	// +kubebuilder:validation:Optional
	OrgGroupIDRef *v2.Reference `json:"orgGroupIdRef,omitempty" tf:"-"`

	// Selector for a OrgGroup in datadog to populate orgGroupId.
	// +kubebuilder:validation:Optional
	OrgGroupIDSelector *v2.Selector `json:"orgGroupIdSelector,omitempty" tf:"-"`

	// fed). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	// The short site name of the organization (e.g., `us1`, `eu1`, `us1-fed`). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	OrgSite *string `json:"orgSite,omitempty" tf:"org_site,omitempty"`

	// (String) The UUID of the organization being exempted from the policy. Must be a valid UUID.
	// The UUID of the organization being exempted from the policy. Must be a valid UUID.
	OrgUUID *string `json:"orgUuid,omitempty" tf:"org_uuid,omitempty"`

	// (String) The UUID of the org group policy the override applies to. Must be a valid UUID.
	// The UUID of the org group policy the override applies to. Must be a valid UUID.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.OrgGroupPolicy
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrgGroupPolicy in datadog to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.Reference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrgGroupPolicy in datadog to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.Selector `json:"policyIdSelector,omitempty" tf:"-"`
}

type OrgGroupPolicyOverrideObservation struct {

	// encoded string. Server-managed.
	// The org's config value at the time the override was created, as a JSON-encoded string. Server-managed.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The UUID of the org group that owns the policy. Must be a valid UUID.
	// The UUID of the org group that owns the policy. Must be a valid UUID.
	OrgGroupID *string `json:"orgGroupId,omitempty" tf:"org_group_id,omitempty"`

	// fed). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	// The short site name of the organization (e.g., `us1`, `eu1`, `us1-fed`). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	OrgSite *string `json:"orgSite,omitempty" tf:"org_site,omitempty"`

	// (String) The UUID of the organization being exempted from the policy. Must be a valid UUID.
	// The UUID of the organization being exempted from the policy. Must be a valid UUID.
	OrgUUID *string `json:"orgUuid,omitempty" tf:"org_uuid,omitempty"`

	// (String) The UUID of the org group policy the override applies to. Must be a valid UUID.
	// The UUID of the org group policy the override applies to. Must be a valid UUID.
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`
}

type OrgGroupPolicyOverrideParameters struct {

	// (String) The UUID of the org group that owns the policy. Must be a valid UUID.
	// The UUID of the org group that owns the policy. Must be a valid UUID.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.OrgGroup
	// +kubebuilder:validation:Optional
	OrgGroupID *string `json:"orgGroupId,omitempty" tf:"org_group_id,omitempty"`

	// Reference to a OrgGroup in datadog to populate orgGroupId.
	// +kubebuilder:validation:Optional
	OrgGroupIDRef *v2.Reference `json:"orgGroupIdRef,omitempty" tf:"-"`

	// Selector for a OrgGroup in datadog to populate orgGroupId.
	// +kubebuilder:validation:Optional
	OrgGroupIDSelector *v2.Selector `json:"orgGroupIdSelector,omitempty" tf:"-"`

	// fed). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	// The short site name of the organization (e.g., `us1`, `eu1`, `us1-fed`). Part of the override's server-side identity; changing it replaces the resource. String length must be at least 1.
	// +kubebuilder:validation:Optional
	OrgSite *string `json:"orgSite,omitempty" tf:"org_site,omitempty"`

	// (String) The UUID of the organization being exempted from the policy. Must be a valid UUID.
	// The UUID of the organization being exempted from the policy. Must be a valid UUID.
	// +kubebuilder:validation:Optional
	OrgUUID *string `json:"orgUuid,omitempty" tf:"org_uuid,omitempty"`

	// (String) The UUID of the org group policy the override applies to. Must be a valid UUID.
	// The UUID of the org group policy the override applies to. Must be a valid UUID.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.OrgGroupPolicy
	// +kubebuilder:validation:Optional
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrgGroupPolicy in datadog to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.Reference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrgGroupPolicy in datadog to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.Selector `json:"policyIdSelector,omitempty" tf:"-"`
}

// OrgGroupPolicyOverrideSpec defines the desired state of OrgGroupPolicyOverride
type OrgGroupPolicyOverrideSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrgGroupPolicyOverrideParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrgGroupPolicyOverrideInitParameters `json:"initProvider,omitempty"`
}

// OrgGroupPolicyOverrideStatus defines the observed state of OrgGroupPolicyOverride.
type OrgGroupPolicyOverrideStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrgGroupPolicyOverrideObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrgGroupPolicyOverride is the Schema for the OrgGroupPolicyOverrides API. Provides a Datadog Org Group Policy Override resource. An override exempts a specific organization from a policy applied at the org group level.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type OrgGroupPolicyOverride struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.orgSite) || (has(self.initProvider) && has(self.initProvider.orgSite))",message="spec.forProvider.orgSite is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.orgUuid) || (has(self.initProvider) && has(self.initProvider.orgUuid))",message="spec.forProvider.orgUuid is a required parameter"
	Spec   OrgGroupPolicyOverrideSpec   `json:"spec"`
	Status OrgGroupPolicyOverrideStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrgGroupPolicyOverrideList contains a list of OrgGroupPolicyOverrides
type OrgGroupPolicyOverrideList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrgGroupPolicyOverride `json:"items"`
}

// Repository type metadata.
var (
	OrgGroupPolicyOverride_Kind             = "OrgGroupPolicyOverride"
	OrgGroupPolicyOverride_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrgGroupPolicyOverride_Kind}.String()
	OrgGroupPolicyOverride_KindAPIVersion   = OrgGroupPolicyOverride_Kind + "." + CRDGroupVersion.String()
	OrgGroupPolicyOverride_GroupVersionKind = CRDGroupVersion.WithKind(OrgGroupPolicyOverride_Kind)
)

func init() {
	SchemeBuilder.Register(&OrgGroupPolicyOverride{}, &OrgGroupPolicyOverrideList{})
}
