/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UserRoleInitParameters struct {

	// (String) ID of the role that the user is assigned to.
	// ID of the role that the user is assigned to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.Role
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in datadog to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in datadog to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// (String) The ID of the user.
	// The ID of the user.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in datadog to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in datadog to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

type UserRoleObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the role that the user is assigned to.
	// ID of the role that the user is assigned to.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) The ID of the user.
	// The ID of the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type UserRoleParameters struct {

	// (String) ID of the role that the user is assigned to.
	// ID of the role that the user is assigned to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.Role
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in datadog to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in datadog to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// (String) The ID of the user.
	// The ID of the user.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/datadog/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in datadog to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in datadog to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

// UserRoleSpec defines the desired state of UserRole
type UserRoleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   UserRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserRoleInitParameters `json:"initProvider,omitempty"`
}

// UserRoleStatus defines the observed state of UserRole.
type UserRoleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserRole is the Schema for the UserRoles API. Provides a Datadog UserRole resource. This can be used to create and manage Datadog User Roles. Conflicts may occur if used together with the datadog_user resource's roles attribute or the datadog_service_account resource's roles attribute. This resource is in beta and is subject to change.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type UserRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserRoleSpec   `json:"spec"`
	Status            UserRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserRoleList contains a list of UserRoles
type UserRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserRole `json:"items"`
}

// Repository type metadata.
var (
	UserRole_Kind             = "UserRole"
	UserRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserRole_Kind}.String()
	UserRole_KindAPIVersion   = UserRole_Kind + "." + CRDGroupVersion.String()
	UserRole_GroupVersionKind = CRDGroupVersion.WithKind(UserRole_Kind)
)

func init() {
	SchemeBuilder.Register(&UserRole{}, &UserRoleList{})
}
