apiVersion: iam.datadog.upbound.io/v1beta1
kind: ServiceAccountApplicationKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccountapplicationkey
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: Application key for managing dashboards
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
