apiVersion: iam.datadog.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    email: new@example.com
    name: Service Account Bar
    rolesRefs:
    - name: datadog_role
