/*
Copyright 2026 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-datadog/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *SyntheticsSuite) ResolveReferences( // ResolveReferences of this SyntheticsSuite.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Tests); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("synthetics.datadog.upbound.io", "v1alpha1", "Test", "TestList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Tests[i3].PublicID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Tests[i3].PublicIDRef,
				Selector:     mg.Spec.ForProvider.Tests[i3].PublicIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Tests[i3].PublicID")
		}
		mg.Spec.ForProvider.Tests[i3].PublicID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Tests[i3].PublicIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Tests); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("synthetics.datadog.upbound.io", "v1alpha1", "Test", "TestList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Tests[i3].PublicID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Tests[i3].PublicIDRef,
				Selector:     mg.Spec.InitProvider.Tests[i3].PublicIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Tests[i3].PublicID")
		}
		mg.Spec.InitProvider.Tests[i3].PublicID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Tests[i3].PublicIDRef = rsp.ResolvedReference

	}

	return nil
}
