apiVersion: agentlessscanning.datadog.m.upbound.io/v1alpha1
kind: GCPScanOptions
metadata:
  annotations:
    meta.upbound.io/example-id: agentlessscanning/v1alpha1/gcpscanoptions
    upjet.upbound.io/manual-intervention: "Requires the project id of a GCP project already integrated with Datadog (via the GCP integration)."
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    cloudFunction: true
    gcpProjectId: company-project-prod
    vulnContainersOs: true
    vulnHostOs: true
