//go:build !ignore_autogenerated

/*
Copyright 2026 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsInitParameters) DeepCopyInto(out *ConditionsInitParameters) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsInitParameters.
func (in *ConditionsInitParameters) DeepCopy() *ConditionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsObservation) DeepCopyInto(out *ConditionsObservation) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsObservation.
func (in *ConditionsObservation) DeepCopy() *ConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsParameters) DeepCopyInto(out *ConditionsParameters) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsParameters.
func (in *ConditionsParameters) DeepCopy() *ConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationInitParameters) DeepCopyInto(out *ConfigurationInitParameters) {
	*out = *in
	if in.AllowIncidentDeletion != nil {
		in, out := &in.AllowIncidentDeletion, &out.AllowIncidentDeletion
		*out = new(bool)
		**out = **in
	}
	if in.AllowWorkflows != nil {
		in, out := &in.AllowWorkflows, &out.AllowWorkflows
		*out = new(bool)
		**out = **in
	}
	if in.CreateMessage != nil {
		in, out := &in.CreateMessage, &out.CreateMessage
		*out = new(string)
		**out = **in
	}
	if in.EditableTimestamps != nil {
		in, out := &in.EditableTimestamps, &out.EditableTimestamps
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidents != nil {
		in, out := &in.PrivateIncidents, &out.PrivateIncidents
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidentsByDefault != nil {
		in, out := &in.PrivateIncidentsByDefault, &out.PrivateIncidentsByDefault
		*out = new(bool)
		**out = **in
	}
	if in.SlugSource != nil {
		in, out := &in.SlugSource, &out.SlugSource
		*out = new(string)
		**out = **in
	}
	if in.TestIncidents != nil {
		in, out := &in.TestIncidents, &out.TestIncidents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationInitParameters.
func (in *ConfigurationInitParameters) DeepCopy() *ConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationObservation) DeepCopyInto(out *ConfigurationObservation) {
	*out = *in
	if in.AllowIncidentDeletion != nil {
		in, out := &in.AllowIncidentDeletion, &out.AllowIncidentDeletion
		*out = new(bool)
		**out = **in
	}
	if in.AllowWorkflows != nil {
		in, out := &in.AllowWorkflows, &out.AllowWorkflows
		*out = new(bool)
		**out = **in
	}
	if in.CreateMessage != nil {
		in, out := &in.CreateMessage, &out.CreateMessage
		*out = new(string)
		**out = **in
	}
	if in.EditableTimestamps != nil {
		in, out := &in.EditableTimestamps, &out.EditableTimestamps
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidents != nil {
		in, out := &in.PrivateIncidents, &out.PrivateIncidents
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidentsByDefault != nil {
		in, out := &in.PrivateIncidentsByDefault, &out.PrivateIncidentsByDefault
		*out = new(bool)
		**out = **in
	}
	if in.SlugSource != nil {
		in, out := &in.SlugSource, &out.SlugSource
		*out = new(string)
		**out = **in
	}
	if in.TestIncidents != nil {
		in, out := &in.TestIncidents, &out.TestIncidents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationObservation.
func (in *ConfigurationObservation) DeepCopy() *ConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationParameters) DeepCopyInto(out *ConfigurationParameters) {
	*out = *in
	if in.AllowIncidentDeletion != nil {
		in, out := &in.AllowIncidentDeletion, &out.AllowIncidentDeletion
		*out = new(bool)
		**out = **in
	}
	if in.AllowWorkflows != nil {
		in, out := &in.AllowWorkflows, &out.AllowWorkflows
		*out = new(bool)
		**out = **in
	}
	if in.CreateMessage != nil {
		in, out := &in.CreateMessage, &out.CreateMessage
		*out = new(string)
		**out = **in
	}
	if in.EditableTimestamps != nil {
		in, out := &in.EditableTimestamps, &out.EditableTimestamps
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidents != nil {
		in, out := &in.PrivateIncidents, &out.PrivateIncidents
		*out = new(bool)
		**out = **in
	}
	if in.PrivateIncidentsByDefault != nil {
		in, out := &in.PrivateIncidentsByDefault, &out.PrivateIncidentsByDefault
		*out = new(bool)
		**out = **in
	}
	if in.SlugSource != nil {
		in, out := &in.SlugSource, &out.SlugSource
		*out = new(string)
		**out = **in
	}
	if in.TestIncidents != nil {
		in, out := &in.TestIncidents, &out.TestIncidents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationParameters.
func (in *ConfigurationParameters) DeepCopy() *ConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentType) DeepCopyInto(out *IncidentType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentType.
func (in *IncidentType) DeepCopy() *IncidentType {
	if in == nil {
		return nil
	}
	out := new(IncidentType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeInitParameters) DeepCopyInto(out *IncidentTypeInitParameters) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ConfigurationInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeInitParameters.
func (in *IncidentTypeInitParameters) DeepCopy() *IncidentTypeInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeList) DeepCopyInto(out *IncidentTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncidentType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeList.
func (in *IncidentTypeList) DeepCopy() *IncidentTypeList {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeObservation) DeepCopyInto(out *IncidentTypeObservation) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ConfigurationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeObservation.
func (in *IncidentTypeObservation) DeepCopy() *IncidentTypeObservation {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeParameters) DeepCopyInto(out *IncidentTypeParameters) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ConfigurationParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeParameters.
func (in *IncidentTypeParameters) DeepCopy() *IncidentTypeParameters {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeSpec) DeepCopyInto(out *IncidentTypeSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeSpec.
func (in *IncidentTypeSpec) DeepCopy() *IncidentTypeSpec {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTypeStatus) DeepCopyInto(out *IncidentTypeStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTypeStatus.
func (in *IncidentTypeStatus) DeepCopy() *IncidentTypeStatus {
	if in == nil {
		return nil
	}
	out := new(IncidentTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataInitParameters) DeepCopyInto(out *MetadataInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataInitParameters.
func (in *MetadataInitParameters) DeepCopy() *MetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataObservation) DeepCopyInto(out *MetadataObservation) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.SearchLimitParam != nil {
		in, out := &in.SearchLimitParam, &out.SearchLimitParam
		*out = new(string)
		**out = **in
	}
	if in.SearchParams != nil {
		in, out := &in.SearchParams, &out.SearchParams
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.SearchQueryParam != nil {
		in, out := &in.SearchQueryParam, &out.SearchQueryParam
		*out = new(string)
		**out = **in
	}
	if in.SearchResultPath != nil {
		in, out := &in.SearchResultPath, &out.SearchResultPath
		*out = new(string)
		**out = **in
	}
	if in.SearchURL != nil {
		in, out := &in.SearchURL, &out.SearchURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataObservation.
func (in *MetadataObservation) DeepCopy() *MetadataObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataParameters) DeepCopyInto(out *MetadataParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataParameters.
func (in *MetadataParameters) DeepCopy() *MetadataParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRule) DeepCopyInto(out *NotificationRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRule.
func (in *NotificationRule) DeepCopy() *NotificationRule {
	if in == nil {
		return nil
	}
	out := new(NotificationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleInitParameters) DeepCopyInto(out *NotificationRuleInitParameters) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Handles != nil {
		in, out := &in.Handles, &out.Handles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationTemplate != nil {
		in, out := &in.NotificationTemplate, &out.NotificationTemplate
		*out = new(string)
		**out = **in
	}
	if in.NotificationTemplateRef != nil {
		in, out := &in.NotificationTemplateRef, &out.NotificationTemplateRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationTemplateSelector != nil {
		in, out := &in.NotificationTemplateSelector, &out.NotificationTemplateSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RenotifyOn != nil {
		in, out := &in.RenotifyOn, &out.RenotifyOn
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(string)
		**out = **in
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleInitParameters.
func (in *NotificationRuleInitParameters) DeepCopy() *NotificationRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleList) DeepCopyInto(out *NotificationRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleList.
func (in *NotificationRuleList) DeepCopy() *NotificationRuleList {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleObservation) DeepCopyInto(out *NotificationRuleObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Handles != nil {
		in, out := &in.Handles, &out.Handles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = new(string)
		**out = **in
	}
	if in.NotificationTemplate != nil {
		in, out := &in.NotificationTemplate, &out.NotificationTemplate
		*out = new(string)
		**out = **in
	}
	if in.RenotifyOn != nil {
		in, out := &in.RenotifyOn, &out.RenotifyOn
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(string)
		**out = **in
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleObservation.
func (in *NotificationRuleObservation) DeepCopy() *NotificationRuleObservation {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleParameters) DeepCopyInto(out *NotificationRuleParameters) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Handles != nil {
		in, out := &in.Handles, &out.Handles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationTemplate != nil {
		in, out := &in.NotificationTemplate, &out.NotificationTemplate
		*out = new(string)
		**out = **in
	}
	if in.NotificationTemplateRef != nil {
		in, out := &in.NotificationTemplateRef, &out.NotificationTemplateRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationTemplateSelector != nil {
		in, out := &in.NotificationTemplateSelector, &out.NotificationTemplateSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RenotifyOn != nil {
		in, out := &in.RenotifyOn, &out.RenotifyOn
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(string)
		**out = **in
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleParameters.
func (in *NotificationRuleParameters) DeepCopy() *NotificationRuleParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleSpec) DeepCopyInto(out *NotificationRuleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleSpec.
func (in *NotificationRuleSpec) DeepCopy() *NotificationRuleSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRuleStatus) DeepCopyInto(out *NotificationRuleStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRuleStatus.
func (in *NotificationRuleStatus) DeepCopy() *NotificationRuleStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplate) DeepCopyInto(out *NotificationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplate.
func (in *NotificationTemplate) DeepCopy() *NotificationTemplate {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateInitParameters) DeepCopyInto(out *NotificationTemplateInitParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateInitParameters.
func (in *NotificationTemplateInitParameters) DeepCopy() *NotificationTemplateInitParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateList) DeepCopyInto(out *NotificationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateList.
func (in *NotificationTemplateList) DeepCopy() *NotificationTemplateList {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateObservation) DeepCopyInto(out *NotificationTemplateObservation) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateObservation.
func (in *NotificationTemplateObservation) DeepCopy() *NotificationTemplateObservation {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateParameters) DeepCopyInto(out *NotificationTemplateParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateParameters.
func (in *NotificationTemplateParameters) DeepCopy() *NotificationTemplateParameters {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateSpec) DeepCopyInto(out *NotificationTemplateSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateSpec.
func (in *NotificationTemplateSpec) DeepCopy() *NotificationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTemplateStatus) DeepCopyInto(out *NotificationTemplateStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTemplateStatus.
func (in *NotificationTemplateStatus) DeepCopy() *NotificationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInitParameters) DeepCopyInto(out *PolicyInitParameters) {
	*out = *in
	if in.IsSingle != nil {
		in, out := &in.IsSingle, &out.IsSingle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInitParameters.
func (in *PolicyInitParameters) DeepCopy() *PolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObservation) DeepCopyInto(out *PolicyObservation) {
	*out = *in
	if in.IsSingle != nil {
		in, out := &in.IsSingle, &out.IsSingle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObservation.
func (in *PolicyObservation) DeepCopy() *PolicyObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyParameters) DeepCopyInto(out *PolicyParameters) {
	*out = *in
	if in.IsSingle != nil {
		in, out := &in.IsSingle, &out.IsSingle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyParameters.
func (in *PolicyParameters) DeepCopy() *PolicyParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedField) DeepCopyInto(out *UserDefinedField) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedField.
func (in *UserDefinedField) DeepCopy() *UserDefinedField {
	if in == nil {
		return nil
	}
	out := new(UserDefinedField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserDefinedField) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldInitParameters) DeepCopyInto(out *UserDefinedFieldInitParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ordinal != nil {
		in, out := &in.Ordinal, &out.Ordinal
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TagKey != nil {
		in, out := &in.TagKey, &out.TagKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ValidValue != nil {
		in, out := &in.ValidValue, &out.ValidValue
		*out = make([]ValidValueInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldInitParameters.
func (in *UserDefinedFieldInitParameters) DeepCopy() *UserDefinedFieldInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldList) DeepCopyInto(out *UserDefinedFieldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserDefinedField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldList.
func (in *UserDefinedFieldList) DeepCopy() *UserDefinedFieldList {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserDefinedFieldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldObservation) DeepCopyInto(out *UserDefinedFieldObservation) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(string)
		**out = **in
	}
	if in.Deleted != nil {
		in, out := &in.Deleted, &out.Deleted
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(MetadataObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ordinal != nil {
		in, out := &in.Ordinal, &out.Ordinal
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Reserved != nil {
		in, out := &in.Reserved, &out.Reserved
		*out = new(bool)
		**out = **in
	}
	if in.TagKey != nil {
		in, out := &in.TagKey, &out.TagKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ValidValue != nil {
		in, out := &in.ValidValue, &out.ValidValue
		*out = make([]ValidValueObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldObservation.
func (in *UserDefinedFieldObservation) DeepCopy() *UserDefinedFieldObservation {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldParameters) DeepCopyInto(out *UserDefinedFieldParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Ordinal != nil {
		in, out := &in.Ordinal, &out.Ordinal
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.TagKey != nil {
		in, out := &in.TagKey, &out.TagKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ValidValue != nil {
		in, out := &in.ValidValue, &out.ValidValue
		*out = make([]ValidValueParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldParameters.
func (in *UserDefinedFieldParameters) DeepCopy() *UserDefinedFieldParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldSpec) DeepCopyInto(out *UserDefinedFieldSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldSpec.
func (in *UserDefinedFieldSpec) DeepCopy() *UserDefinedFieldSpec {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldStatus) DeepCopyInto(out *UserDefinedFieldStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldStatus.
func (in *UserDefinedFieldStatus) DeepCopy() *UserDefinedFieldStatus {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRole) DeepCopyInto(out *UserDefinedRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRole.
func (in *UserDefinedRole) DeepCopy() *UserDefinedRole {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserDefinedRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleInitParameters) DeepCopyInto(out *UserDefinedRoleInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(PolicyInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleInitParameters.
func (in *UserDefinedRoleInitParameters) DeepCopy() *UserDefinedRoleInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleList) DeepCopyInto(out *UserDefinedRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserDefinedRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleList.
func (in *UserDefinedRoleList) DeepCopy() *UserDefinedRoleList {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserDefinedRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleObservation) DeepCopyInto(out *UserDefinedRoleObservation) {
	*out = *in
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(PolicyObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleObservation.
func (in *UserDefinedRoleObservation) DeepCopy() *UserDefinedRoleObservation {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleParameters) DeepCopyInto(out *UserDefinedRoleParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IncidentType != nil {
		in, out := &in.IncidentType, &out.IncidentType
		*out = new(string)
		**out = **in
	}
	if in.IncidentTypeRef != nil {
		in, out := &in.IncidentTypeRef, &out.IncidentTypeRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentTypeSelector != nil {
		in, out := &in.IncidentTypeSelector, &out.IncidentTypeSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(PolicyParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleParameters.
func (in *UserDefinedRoleParameters) DeepCopy() *UserDefinedRoleParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleSpec) DeepCopyInto(out *UserDefinedRoleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleSpec.
func (in *UserDefinedRoleSpec) DeepCopy() *UserDefinedRoleSpec {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedRoleStatus) DeepCopyInto(out *UserDefinedRoleStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedRoleStatus.
func (in *UserDefinedRoleStatus) DeepCopy() *UserDefinedRoleStatus {
	if in == nil {
		return nil
	}
	out := new(UserDefinedRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidValueInitParameters) DeepCopyInto(out *ValidValueInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ShortDescription != nil {
		in, out := &in.ShortDescription, &out.ShortDescription
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidValueInitParameters.
func (in *ValidValueInitParameters) DeepCopy() *ValidValueInitParameters {
	if in == nil {
		return nil
	}
	out := new(ValidValueInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidValueObservation) DeepCopyInto(out *ValidValueObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ShortDescription != nil {
		in, out := &in.ShortDescription, &out.ShortDescription
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidValueObservation.
func (in *ValidValueObservation) DeepCopy() *ValidValueObservation {
	if in == nil {
		return nil
	}
	out := new(ValidValueObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidValueParameters) DeepCopyInto(out *ValidValueParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ShortDescription != nil {
		in, out := &in.ShortDescription, &out.ShortDescription
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidValueParameters.
func (in *ValidValueParameters) DeepCopy() *ValidValueParameters {
	if in == nil {
		return nil
	}
	out := new(ValidValueParameters)
	in.DeepCopyInto(out)
	return out
}
