// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DailyLimitResetInitParameters struct {

	// (String) String in HH:00 format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	// String in `HH:00` format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	ResetTime *string `json:"resetTime,omitempty" tf:"reset_time,omitempty"`

	// |+)HH:00 format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	// String in `(-|+)HH:00` format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	ResetUtcOffset *string `json:"resetUtcOffset,omitempty" tf:"reset_utc_offset,omitempty"`
}

type DailyLimitResetObservation struct {

	// (String) String in HH:00 format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	// String in `HH:00` format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	ResetTime *string `json:"resetTime,omitempty" tf:"reset_time,omitempty"`

	// |+)HH:00 format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	// String in `(-|+)HH:00` format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	ResetUtcOffset *string `json:"resetUtcOffset,omitempty" tf:"reset_utc_offset,omitempty"`
}

type DailyLimitResetParameters struct {

	// (String) String in HH:00 format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	// String in `HH:00` format representing the time of day the daily limit should be reset. The hours must be between 00 and 23 (inclusive).
	// +kubebuilder:validation:Optional
	ResetTime *string `json:"resetTime" tf:"reset_time,omitempty"`

	// |+)HH:00 format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	// String in `(-|+)HH:00` format representing the UTC offset to apply to the given reset time. The hours must be between -12 and +14 (inclusive).
	// +kubebuilder:validation:Optional
	ResetUtcOffset *string `json:"resetUtcOffset" tf:"reset_utc_offset,omitempty"`
}

type ExclusionFilterFilterInitParameters struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Only logs matching the filter criteria and the query of the parent index will be considered for this exclusion filter.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (Number) The fraction of logs excluded by the exclusion filter, when active.
	// The fraction of logs excluded by the exclusion filter, when active.
	SampleRate *float64 `json:"sampleRate,omitempty" tf:"sample_rate,omitempty"`
}

type ExclusionFilterFilterObservation struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Only logs matching the filter criteria and the query of the parent index will be considered for this exclusion filter.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (Number) The fraction of logs excluded by the exclusion filter, when active.
	// The fraction of logs excluded by the exclusion filter, when active.
	SampleRate *float64 `json:"sampleRate,omitempty" tf:"sample_rate,omitempty"`
}

type ExclusionFilterFilterParameters struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Only logs matching the filter criteria and the query of the parent index will be considered for this exclusion filter.
	// +kubebuilder:validation:Optional
	Query *string `json:"query,omitempty" tf:"query,omitempty"`

	// (Number) The fraction of logs excluded by the exclusion filter, when active.
	// The fraction of logs excluded by the exclusion filter, when active.
	// +kubebuilder:validation:Optional
	SampleRate *float64 `json:"sampleRate,omitempty" tf:"sample_rate,omitempty"`
}

type ExclusionFilterInitParameters struct {

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	Filter []ExclusionFilterFilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (Boolean) A boolean stating if the exclusion is active or not.
	// A boolean stating if the exclusion is active or not.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) The name of the index.
	// The name of the exclusion filter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ExclusionFilterObservation struct {

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	Filter []ExclusionFilterFilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	// (Boolean) A boolean stating if the exclusion is active or not.
	// A boolean stating if the exclusion is active or not.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) The name of the index.
	// The name of the exclusion filter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ExclusionFilterParameters struct {

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	// +kubebuilder:validation:Optional
	Filter []ExclusionFilterFilterParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (Boolean) A boolean stating if the exclusion is active or not.
	// A boolean stating if the exclusion is active or not.
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (String) The name of the index.
	// The name of the exclusion filter.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IndexFilterInitParameters struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type IndexFilterObservation struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type IndexFilterParameters struct {

	// (String) Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// Logs filter criteria. Only logs matching this filter criteria are considered for this index.
	// +kubebuilder:validation:Optional
	Query *string `json:"query" tf:"query,omitempty"`
}

type IndexInitParameters struct {

	// limited.
	// The number of log events you can send in this index per day before you are rate-limited.
	DailyLimit *float64 `json:"dailyLimit,omitempty" tf:"daily_limit,omitempty"`

	// (Block List, Max: 1) Object containing options to override the default daily limit reset time. (see below for nested schema)
	// Object containing options to override the default daily limit reset time.
	DailyLimitReset []DailyLimitResetInitParameters `json:"dailyLimitReset,omitempty" tf:"daily_limit_reset,omitempty"`

	// (Number) A percentage threshold of the daily quota at which a Datadog warning event is generated.
	// A percentage threshold of the daily quota at which a Datadog warning event is generated.
	DailyLimitWarningThresholdPercentage *float64 `json:"dailyLimitWarningThresholdPercentage,omitempty" tf:"daily_limit_warning_threshold_percentage,omitempty"`

	// (Boolean) If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	// If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	DisableDailyLimit *bool `json:"disableDailyLimit,omitempty" tf:"disable_daily_limit,omitempty"`

	// (Block List) List of exclusion filters. (see below for nested schema)
	// List of exclusion filters.
	ExclusionFilter []ExclusionFilterInitParameters `json:"exclusionFilter,omitempty" tf:"exclusion_filter,omitempty"`

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	// Logs filter
	Filter []IndexFilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The name of the index.
	// The name of the index.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of days before logs are deleted from this index.
	// The number of days before logs are deleted from this index.
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

type IndexObservation struct {

	// limited.
	// The number of log events you can send in this index per day before you are rate-limited.
	DailyLimit *float64 `json:"dailyLimit,omitempty" tf:"daily_limit,omitempty"`

	// (Block List, Max: 1) Object containing options to override the default daily limit reset time. (see below for nested schema)
	// Object containing options to override the default daily limit reset time.
	DailyLimitReset []DailyLimitResetObservation `json:"dailyLimitReset,omitempty" tf:"daily_limit_reset,omitempty"`

	// (Number) A percentage threshold of the daily quota at which a Datadog warning event is generated.
	// A percentage threshold of the daily quota at which a Datadog warning event is generated.
	DailyLimitWarningThresholdPercentage *float64 `json:"dailyLimitWarningThresholdPercentage,omitempty" tf:"daily_limit_warning_threshold_percentage,omitempty"`

	// (Boolean) If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	// If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	DisableDailyLimit *bool `json:"disableDailyLimit,omitempty" tf:"disable_daily_limit,omitempty"`

	// (Block List) List of exclusion filters. (see below for nested schema)
	// List of exclusion filters.
	ExclusionFilter []ExclusionFilterObservation `json:"exclusionFilter,omitempty" tf:"exclusion_filter,omitempty"`

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	// Logs filter
	Filter []IndexFilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the index.
	// The name of the index.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of days before logs are deleted from this index.
	// The number of days before logs are deleted from this index.
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

type IndexParameters struct {

	// limited.
	// The number of log events you can send in this index per day before you are rate-limited.
	// +kubebuilder:validation:Optional
	DailyLimit *float64 `json:"dailyLimit,omitempty" tf:"daily_limit,omitempty"`

	// (Block List, Max: 1) Object containing options to override the default daily limit reset time. (see below for nested schema)
	// Object containing options to override the default daily limit reset time.
	// +kubebuilder:validation:Optional
	DailyLimitReset []DailyLimitResetParameters `json:"dailyLimitReset,omitempty" tf:"daily_limit_reset,omitempty"`

	// (Number) A percentage threshold of the daily quota at which a Datadog warning event is generated.
	// A percentage threshold of the daily quota at which a Datadog warning event is generated.
	// +kubebuilder:validation:Optional
	DailyLimitWarningThresholdPercentage *float64 `json:"dailyLimitWarningThresholdPercentage,omitempty" tf:"daily_limit_warning_threshold_percentage,omitempty"`

	// (Boolean) If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	// If true, sets the daily_limit value to null and the index is not limited on a daily basis (any specified daily_limit value in the request is ignored). If false or omitted, the index's current daily_limit is maintained.
	// +kubebuilder:validation:Optional
	DisableDailyLimit *bool `json:"disableDailyLimit,omitempty" tf:"disable_daily_limit,omitempty"`

	// (Block List) List of exclusion filters. (see below for nested schema)
	// List of exclusion filters.
	// +kubebuilder:validation:Optional
	ExclusionFilter []ExclusionFilterParameters `json:"exclusionFilter,omitempty" tf:"exclusion_filter,omitempty"`

	// (Block List, Min: 1, Max: 1) Logs filter (see below for nested schema)
	// Logs filter
	// +kubebuilder:validation:Optional
	Filter []IndexFilterParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The name of the index.
	// The name of the index.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of days before logs are deleted from this index.
	// The number of days before logs are deleted from this index.
	// +kubebuilder:validation:Optional
	RetentionDays *float64 `json:"retentionDays,omitempty" tf:"retention_days,omitempty"`
}

// IndexSpec defines the desired state of Index
type IndexSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IndexParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IndexInitParameters `json:"initProvider,omitempty"`
}

// IndexStatus defines the observed state of Index.
type IndexStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IndexObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Index is the Schema for the Indexs API. Provides a Datadog Logs Index API resource. This can be used to create and manage Datadog logs indexes. Reach out to support to delete a logs index.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type Index struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.filter) || (has(self.initProvider) && has(self.initProvider.filter))",message="spec.forProvider.filter is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IndexSpec   `json:"spec"`
	Status IndexStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IndexList contains a list of Indexs
type IndexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Index `json:"items"`
}

// Repository type metadata.
var (
	Index_Kind             = "Index"
	Index_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Index_Kind}.String()
	Index_KindAPIVersion   = Index_Kind + "." + CRDGroupVersion.String()
	Index_GroupVersionKind = CRDGroupVersion.WithKind(Index_Kind)
)

func init() {
	SchemeBuilder.Register(&Index{}, &IndexList{})
}
