// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConditionalRecipientsInitParameters struct {

	// (Block List) Conditions of the notification rule. (see below for nested schema)
	// Conditions of the notification rule.
	Conditions []ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Set of String) If none of the conditions applied, fallback_recipients will get notified.
	// If none of the `conditions` applied, `fallback_recipients` will get notified.
	// +listType=set
	FallbackRecipients []*string `json:"fallbackRecipients,omitempty" tf:"fallback_recipients,omitempty"`
}

type ConditionalRecipientsObservation struct {

	// (Block List) Conditions of the notification rule. (see below for nested schema)
	// Conditions of the notification rule.
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Set of String) If none of the conditions applied, fallback_recipients will get notified.
	// If none of the `conditions` applied, `fallback_recipients` will get notified.
	// +listType=set
	FallbackRecipients []*string `json:"fallbackRecipients,omitempty" tf:"fallback_recipients,omitempty"`
}

type ConditionalRecipientsParameters struct {

	// (Block List) Conditions of the notification rule. (see below for nested schema)
	// Conditions of the notification rule.
	// +kubebuilder:validation:Optional
	Conditions []ConditionsParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Set of String) If none of the conditions applied, fallback_recipients will get notified.
	// If none of the `conditions` applied, `fallback_recipients` will get notified.
	// +kubebuilder:validation:Optional
	// +listType=set
	FallbackRecipients []*string `json:"fallbackRecipients,omitempty" tf:"fallback_recipients,omitempty"`
}

type ConditionsInitParameters struct {

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// A list of recipients to notify. Uses the same format as the monitor message field. Must not start with an '@'.
	// +listType=set
	Recipients []*string `json:"recipients,omitempty" tf:"recipients,omitempty"`

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using `transition_type:<status>` (for example `transition_type:is_alert`) or a single tag `key:value pair` (for example `env:prod`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type ConditionsObservation struct {

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// A list of recipients to notify. Uses the same format as the monitor message field. Must not start with an '@'.
	// +listType=set
	Recipients []*string `json:"recipients,omitempty" tf:"recipients,omitempty"`

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using `transition_type:<status>` (for example `transition_type:is_alert`) or a single tag `key:value pair` (for example `env:prod`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type ConditionsParameters struct {

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// A list of recipients to notify. Uses the same format as the monitor message field. Must not start with an '@'.
	// +kubebuilder:validation:Optional
	// +listType=set
	Recipients []*string `json:"recipients" tf:"recipients,omitempty"`

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using `transition_type:<status>` (for example `transition_type:is_alert`) or a single tag `key:value pair` (for example `env:prod`).
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope" tf:"scope,omitempty"`
}

type FilterInitParameters struct {

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// A scope expression composed of `key:value` pairs (such as `env:prod`) with boolean operators (AND, OR, NOT) and parentheses for grouping.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Set of String) A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FilterObservation struct {

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// A scope expression composed of `key:value` pairs (such as `env:prod`) with boolean operators (AND, OR, NOT) and parentheses for grouping.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Set of String) A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FilterParameters struct {

	// (String) Defines the condition under which the recipients are notified. Supported formats: Monitor status condition using transition_type:<status> (for example transition_type:is_alert) or a single tag key:value pair (for example env:prod).
	// A scope expression composed of `key:value` pairs (such as `env:prod`) with boolean operators (AND, OR, NOT) and parentheses for grouping.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Set of String) A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// A list of tag key:value pairs (e.g. team:product). All tags must match (AND semantics).
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type NotificationRuleInitParameters struct {

	// (Block, Optional) Use conditional recipients to define different recipients for different situations. Cannot be used with recipients. (see below for nested schema)
	// Use conditional recipients to define different recipients for different situations. Cannot be used with `recipients`.
	ConditionalRecipients []ConditionalRecipientsInitParameters `json:"conditionalRecipients,omitempty" tf:"conditional_recipients,omitempty"`

	// (Block, Optional) Specifies the matching criteria for monitor notifications. (see below for nested schema)
	// Specifies the matching criteria for monitor notifications.
	Filter []FilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The name of the monitor notification rule.
	// The name of the monitor notification rule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// List of recipients to notify. Cannot be used with `conditional_recipients`.
	// +listType=set
	Recipients []*string `json:"recipients,omitempty" tf:"recipients,omitempty"`
}

type NotificationRuleObservation struct {

	// (Block, Optional) Use conditional recipients to define different recipients for different situations. Cannot be used with recipients. (see below for nested schema)
	// Use conditional recipients to define different recipients for different situations. Cannot be used with `recipients`.
	ConditionalRecipients []ConditionalRecipientsObservation `json:"conditionalRecipients,omitempty" tf:"conditional_recipients,omitempty"`

	// (Block, Optional) Specifies the matching criteria for monitor notifications. (see below for nested schema)
	// Specifies the matching criteria for monitor notifications.
	Filter []FilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the monitor notification rule.
	// The name of the monitor notification rule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// List of recipients to notify. Cannot be used with `conditional_recipients`.
	// +listType=set
	Recipients []*string `json:"recipients,omitempty" tf:"recipients,omitempty"`
}

type NotificationRuleParameters struct {

	// (Block, Optional) Use conditional recipients to define different recipients for different situations. Cannot be used with recipients. (see below for nested schema)
	// Use conditional recipients to define different recipients for different situations. Cannot be used with `recipients`.
	// +kubebuilder:validation:Optional
	ConditionalRecipients []ConditionalRecipientsParameters `json:"conditionalRecipients,omitempty" tf:"conditional_recipients,omitempty"`

	// (Block, Optional) Specifies the matching criteria for monitor notifications. (see below for nested schema)
	// Specifies the matching criteria for monitor notifications.
	// +kubebuilder:validation:Optional
	Filter []FilterParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The name of the monitor notification rule.
	// The name of the monitor notification rule.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) List of recipients to notify. Cannot be used with conditional_recipients.
	// List of recipients to notify. Cannot be used with `conditional_recipients`.
	// +kubebuilder:validation:Optional
	// +listType=set
	Recipients []*string `json:"recipients,omitempty" tf:"recipients,omitempty"`
}

// NotificationRuleSpec defines the desired state of NotificationRule
type NotificationRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NotificationRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NotificationRuleInitParameters `json:"initProvider,omitempty"`
}

// NotificationRuleStatus defines the observed state of NotificationRule.
type NotificationRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NotificationRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NotificationRule is the Schema for the NotificationRules API. Provides a Datadog MonitorNotificationRule resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type NotificationRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.conditionalRecipients) || (has(self.initProvider) && has(self.initProvider.conditionalRecipients))",message="spec.forProvider.conditionalRecipients is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   NotificationRuleSpec   `json:"spec"`
	Status NotificationRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NotificationRuleList contains a list of NotificationRules
type NotificationRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NotificationRule `json:"items"`
}

// Repository type metadata.
var (
	NotificationRule_Kind             = "NotificationRule"
	NotificationRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NotificationRule_Kind}.String()
	NotificationRule_KindAPIVersion   = NotificationRule_Kind + "." + CRDGroupVersion.String()
	NotificationRule_GroupVersionKind = CRDGroupVersion.WithKind(NotificationRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NotificationRule{}, &NotificationRuleList{})
}
