apiVersion: datadog.m.upbound.io/v1alpha1
kind: OrgGroup
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/orggroup
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: Production Environments
