apiVersion: datadog.m.upbound.io/v1alpha1
kind: OrgGroupPolicyOverride
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/orggrouppolicyoverride
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    orgGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: prod
    orgSite: us1
    orgUuid: ff4a8255-6931-58d1-add0-a6b3602d5421
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: widget_copy_paste

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: OrgGroup
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/orggrouppolicyoverride
  labels:
    testing.upbound.io/example-name: prod
  name: prod
  namespace: upbound-system
spec:
  forProvider:
    name: Production Environments

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: OrgGroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/orggrouppolicyoverride
  labels:
    testing.upbound.io/example-name: exempt_org
  name: exempt-org
  namespace: upbound-system
spec:
  forProvider:
    orgGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: prod
    orgUuid: ff4a8255-6931-58d1-add0-a6b3602d5421

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: OrgGroupPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/orggrouppolicyoverride
  labels:
    testing.upbound.io/example-name: widget_copy_paste
  name: widget-copy-paste
  namespace: upbound-system
spec:
  forProvider:
    content: '${jsonencode({ "org_config" : false })}'
    enforcementTier: OVERRIDE_ALLOWED
    orgGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: prod
    policyName: is_widget_copy_paste_enabled
