apiVersion: datadog.m.upbound.io/v1alpha1
kind: RUMExclusionFilter
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/rumexclusionfilter
  labels:
    testing.upbound.io/example-name: testing_rum_exclusion_filter
  name: testing-rum-exclusion-filter
  namespace: upbound-system
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    enabled: true
    eventType: error
    name: testing.rum.exclusion_filter
    query: '@error.message:*extension*'
