apiVersion: datadog.m.upbound.io/v1alpha1
kind: TeamMembership
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teammembership
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    role: admin
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teammembership
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    description: Example team
    handle: example-team-updated
    name: Example Team-updated

---

apiVersion: datadog.m.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/teammembership
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    email: new@example.com
