apiVersion: datadog.m.upbound.io/v1alpha1
kind: WebhookOauth2ClientCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/webhookoauth2clientcredentials
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    accessTokenUrl: https://example.com/oauth2/token
    audience: https://example.com/api
    clientId: example-client-id
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    name: example-auth-method
    scope: read write
