apiVersion: integration.datadog.upbound.io/v1beta1
kind: AwsTagFilter
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This resource needs AWS integration
    meta.upbound.io/example-id: integration/v1beta1/awstagfilter
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accountId: <aws-account-id>
    namespace: sqs
    tagFilterStr: key:value
