apiVersion: integration.datadog.upbound.io/v1beta1
kind: OpsgenieServiceObject
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This resource needs opsgenie integration
    meta.upbound.io/example-id: integration/v1beta1/opsgenieserviceobject
  labels:
    testing.upbound.io/example-name: example_service_name
  name: example-service-name
spec:
  forProvider:
    name: example_service_name
    opsgenieApiKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: us
