apiVersion: datadog.upbound.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/role
  labels:
    testing.upbound.io/example-name: api_key_manager
  name: api-key-manager
spec:
  forProvider:
    name: API Key Manager
    permission:
    - id: ${data.datadog_permissions.dd_perms.permissions.api_keys_read}
    - id: ${data.datadog_permissions.dd_perms.permissions.api_keys_write}
