apiVersion: incident.datadog.m.upbound.io/v1alpha1
kind: UserDefinedRole
metadata:
  annotations:
    meta.upbound.io/example-id: incident/v1alpha1/userdefinedrole
  labels:
    testing.upbound.io/example-name: tech_lead
  name: tech-lead
  namespace: upbound-system
spec:
  forProvider:
    description: The technical lead for the incident.
    incidentTypeSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: Tech Lead
    policy:
      isSingle: true

---

apiVersion: incident.datadog.m.upbound.io/v1alpha1
kind: IncidentType
metadata:
  annotations:
    meta.upbound.io/example-id: incident.datadog/v1alpha1/userdefinedrole
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Security-related incidents requiring immediate attention
    name: Security Incident
