apiVersion: azure.upbound.io/v1alpha1
kind: UcConfig
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/ucconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountId: 12345678-1234-abcd-1234-123456789012
    clientId: 87654321-4321-dcba-4321-210987654321
    scope: /subscriptions/12345678-1234-abcd-1234-123456789012
