apiVersion: slo.datadog.upbound.io/v1beta1
kind: Correction
metadata:
  annotations:
    meta.upbound.io/example-id: slo/v1beta1/correction
  labels:
    testing.upbound.io/example-name: example_slo_correction
  name: example-slo-correction
spec:
  forProvider:
    category: Scheduled Maintenance
    description: correction example
    sloIdSelector:
      matchLabels:
        testing.upbound.io/example-name: correction
    start: 1817631983
    end: 1820310383
    timezone: UTC

---

apiVersion: slo.datadog.upbound.io/v1beta1
kind: ServiceLevelObjective
metadata:
  annotations:
    meta.upbound.io/example-id: slo/v1beta1/servicelevelobjective
  labels:
    testing.upbound.io/example-name: correction
  name: correction
spec:
  forProvider:
    description: My custom metric SLO
    name: correction
    query:
      denominator: sum:my.custom.count.metric{*}.as_count()
      numerator: sum:my.custom.count.metric{type:good_events}.as_count()
    tags:
      - foo:bar
      - baz
    targetThreshold: 99.9
    thresholds:
      - target: 99.9
        timeframe: 7d
        warning: 99.99
      - target: 99.9
        timeframe: 30d
        warning: 99.99
    timeframe: 30d
    type: metric
    warningThreshold: 99.99
