/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MetadataInitParameters struct {
}

type MetadataObservation struct {

	// (String) The section in which the field appears: what_happened or why_it_happened. When unset, the field appears in the Attributes section.
	// The category of the autocomplete source.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) The query parameter used to limit the number of autocomplete results.
	// The query parameter used to limit the number of autocomplete results.
	SearchLimitParam *string `json:"searchLimitParam,omitempty" tf:"search_limit_param,omitempty"`

	// (Map of String) Additional query parameters to include in the search URL.
	// Additional query parameters to include in the search URL.
	// +mapType=granular
	SearchParams map[string]*string `json:"searchParams,omitempty" tf:"search_params,omitempty"`

	// (String) The query parameter used to pass typed input to the search URL.
	// The query parameter used to pass typed input to the search URL.
	SearchQueryParam *string `json:"searchQueryParam,omitempty" tf:"search_query_param,omitempty"`

	// (String) The JSON path to the results in the response body.
	// The JSON path to the results in the response body.
	SearchResultPath *string `json:"searchResultPath,omitempty" tf:"search_result_path,omitempty"`

	// (String) The URL used to populate autocomplete options.
	// The URL used to populate autocomplete options.
	SearchURL *string `json:"searchUrl,omitempty" tf:"search_url,omitempty"`
}

type MetadataParameters struct {
}

type UserDefinedFieldInitParameters struct {

	// (String) The section in which the field appears: what_happened or why_it_happened. When unset, the field appears in the Attributes section.
	// The section in which the field appears: `what_happened` or `why_it_happened`. When unset, the field appears in the Attributes section.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) The default value for the field. Must be one of the valid values when valid_values is set.
	// The default value for the field. Must be one of the valid values when `valid_values` is set.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	// The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/incident.datadog/v1alpha1.IncidentType
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	IncidentType *string `json:"incidentType,omitempty" tf:"incident_type,omitempty"`

	// Reference to a IncidentType in incident.datadog to populate incidentType.
	// +kubebuilder:validation:Optional
	IncidentTypeRef *v2.Reference `json:"incidentTypeRef,omitempty" tf:"-"`

	// Selector for a IncidentType in incident.datadog to populate incidentType.
	// +kubebuilder:validation:Optional
	IncidentTypeSelector *v2.Selector `json:"incidentTypeSelector,omitempty" tf:"-"`

	// (String) The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	// The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	// A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	Ordinal *string `json:"ordinal,omitempty" tf:"ordinal,omitempty"`

	// (Boolean) When true, users must fill out this field on incidents. Defaults to false.
	// When true, users must fill out this field on incidents. Defaults to `false`.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	// For metric tag-type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	TagKey *string `json:"tagKey,omitempty" tf:"tag_key,omitempty"`

	// (String) The data type of the field. Changing the type forces a new resource. Valid values are dropdown, multiselect, textbox, textarray, metrictag, autocomplete, number, datetime.
	// The data type of the field. Changing the type forces a new resource. Valid values are `dropdown`, `multiselect`, `textbox`, `textarray`, `metrictag`, `autocomplete`, `number`, `datetime`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Block Set) A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set. (see below for nested schema)
	// A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set.
	ValidValue []ValidValueInitParameters `json:"validValue,omitempty" tf:"valid_value,omitempty"`
}

type UserDefinedFieldObservation struct {

	// (String) The section in which the field appears: what_happened or why_it_happened. When unset, the field appears in the Attributes section.
	// The section in which the field appears: `what_happened` or `why_it_happened`. When unset, the field appears in the Attributes section.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) Timestamp when the field was created.
	// Timestamp when the field was created.
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	// (String) The default value for the field. Must be one of the valid values when valid_values is set.
	// The default value for the field. Must be one of the valid values when `valid_values` is set.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// deleted, or null if not deleted.
	// Timestamp when the field was soft-deleted, or null if not deleted.
	Deleted *string `json:"deleted,omitempty" tf:"deleted,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// defined field.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	// The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	IncidentType *string `json:"incidentType,omitempty" tf:"incident_type,omitempty"`

	// type fields, describing how to populate autocomplete options. Populated by the server for supported fields. (see below for nested schema)
	Metadata *MetadataObservation `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Timestamp when the field was last modified.
	// Timestamp when the field was last modified.
	Modified *string `json:"modified,omitempty" tf:"modified,omitempty"`

	// (String) The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	// The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	// A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	Ordinal *string `json:"ordinal,omitempty" tf:"ordinal,omitempty"`

	// (Boolean) When true, users must fill out this field on incidents. Defaults to false.
	// When true, users must fill out this field on incidents. Defaults to `false`.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (Boolean) When true, this field is reserved for system use and cannot be deleted.
	// When true, this field is reserved for system use and cannot be deleted.
	Reserved *bool `json:"reserved,omitempty" tf:"reserved,omitempty"`

	// type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	// For metric tag-type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	TagKey *string `json:"tagKey,omitempty" tf:"tag_key,omitempty"`

	// (String) The data type of the field. Changing the type forces a new resource. Valid values are dropdown, multiselect, textbox, textarray, metrictag, autocomplete, number, datetime.
	// The data type of the field. Changing the type forces a new resource. Valid values are `dropdown`, `multiselect`, `textbox`, `textarray`, `metrictag`, `autocomplete`, `number`, `datetime`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Block Set) A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set. (see below for nested schema)
	// A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set.
	ValidValue []ValidValueObservation `json:"validValue,omitempty" tf:"valid_value,omitempty"`
}

type UserDefinedFieldParameters struct {

	// (String) The section in which the field appears: what_happened or why_it_happened. When unset, the field appears in the Attributes section.
	// The section in which the field appears: `what_happened` or `why_it_happened`. When unset, the field appears in the Attributes section.
	// +kubebuilder:validation:Optional
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (String) The default value for the field. Must be one of the valid values when valid_values is set.
	// The default value for the field. Must be one of the valid values when `valid_values` is set.
	// +kubebuilder:validation:Optional
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	// The ID of the incident type this field is associated with. Changing the incident type forces a new resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-datadog/apis/cluster/incident.datadog/v1alpha1.IncidentType
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	IncidentType *string `json:"incidentType,omitempty" tf:"incident_type,omitempty"`

	// Reference to a IncidentType in incident.datadog to populate incidentType.
	// +kubebuilder:validation:Optional
	IncidentTypeRef *v2.Reference `json:"incidentTypeRef,omitempty" tf:"-"`

	// Selector for a IncidentType in incident.datadog to populate incidentType.
	// +kubebuilder:validation:Optional
	IncidentTypeSelector *v2.Selector `json:"incidentTypeSelector,omitempty" tf:"-"`

	// (String) The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	// The unique identifier of the field. Must start with a letter or digit and contain only letters, digits, underscores, or periods. Changing the name forces a new resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	// A decimal string representing the field's display order in the UI. Assigned by the server when not provided.
	// +kubebuilder:validation:Optional
	Ordinal *string `json:"ordinal,omitempty" tf:"ordinal,omitempty"`

	// (Boolean) When true, users must fill out this field on incidents. Defaults to false.
	// When true, users must fill out this field on incidents. Defaults to `false`.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	// For metric tag-type fields only, the metric tag key that powers the autocomplete options. Changing the tag key forces a new resource.
	// +kubebuilder:validation:Optional
	TagKey *string `json:"tagKey,omitempty" tf:"tag_key,omitempty"`

	// (String) The data type of the field. Changing the type forces a new resource. Valid values are dropdown, multiselect, textbox, textarray, metrictag, autocomplete, number, datetime.
	// The data type of the field. Changing the type forces a new resource. Valid values are `dropdown`, `multiselect`, `textbox`, `textarray`, `metrictag`, `autocomplete`, `number`, `datetime`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Block Set) A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set. (see below for nested schema)
	// A set of allowed values for dropdown, multiselect, and autocomplete fields; specify one block per value. Limited to 1000 values. The API does not preserve ordering, so this is modeled as an unordered set.
	// +kubebuilder:validation:Optional
	ValidValue []ValidValueParameters `json:"validValue,omitempty" tf:"valid_value,omitempty"`
}

type ValidValueInitParameters struct {

	// (String) A detailed description of the valid value.
	// A detailed description of the valid value.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable display name for this value.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) A short description of the valid value.
	// A short description of the valid value.
	ShortDescription *string `json:"shortDescription,omitempty" tf:"short_description,omitempty"`

	// (String) The identifier that is stored when this option is selected.
	// The identifier that is stored when this option is selected.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ValidValueObservation struct {

	// (String) A detailed description of the valid value.
	// A detailed description of the valid value.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable display name for this value.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) A short description of the valid value.
	// A short description of the valid value.
	ShortDescription *string `json:"shortDescription,omitempty" tf:"short_description,omitempty"`

	// (String) The identifier that is stored when this option is selected.
	// The identifier that is stored when this option is selected.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ValidValueParameters struct {

	// (String) A detailed description of the valid value.
	// A detailed description of the valid value.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// readable name shown in the UI. Defaults to a formatted version of the name if not provided.
	// The human-readable display name for this value.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName" tf:"display_name,omitempty"`

	// (String) A short description of the valid value.
	// A short description of the valid value.
	// +kubebuilder:validation:Optional
	ShortDescription *string `json:"shortDescription,omitempty" tf:"short_description,omitempty"`

	// (String) The identifier that is stored when this option is selected.
	// The identifier that is stored when this option is selected.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// UserDefinedFieldSpec defines the desired state of UserDefinedField
type UserDefinedFieldSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   UserDefinedFieldParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserDefinedFieldInitParameters `json:"initProvider,omitempty"`
}

// UserDefinedFieldStatus defines the observed state of UserDefinedField.
type UserDefinedFieldStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserDefinedFieldObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserDefinedField is the Schema for the UserDefinedFields API. Provides a Datadog incident user-defined field resource. This can be used to create and manage custom fields on Datadog incidents. Note: This resource targets an endpoint that is in preview and is subject to change.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,datadog}
type UserDefinedField struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   UserDefinedFieldSpec   `json:"spec"`
	Status UserDefinedFieldStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserDefinedFieldList contains a list of UserDefinedFields
type UserDefinedFieldList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserDefinedField `json:"items"`
}

// Repository type metadata.
var (
	UserDefinedField_Kind             = "UserDefinedField"
	UserDefinedField_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserDefinedField_Kind}.String()
	UserDefinedField_KindAPIVersion   = UserDefinedField_Kind + "." + CRDGroupVersion.String()
	UserDefinedField_GroupVersionKind = CRDGroupVersion.WithKind(UserDefinedField_Kind)
)

func init() {
	SchemeBuilder.Register(&UserDefinedField{}, &UserDefinedFieldList{})
}
