apiVersion: iam.datadog.upbound.io/v1beta1
kind: ServiceAccountApplicationKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccountapplicationkey
  labels:
    testing.upbound.io/example-name: sa_app_key
  name: uptest
spec:
  forProvider:
    name: Application key for managing dashboards
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sa_app_key

---

apiVersion: iam.datadog.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: sa_app_key
  name: app-key
spec:
  forProvider:
    email: app-key@example.com
    name: Service Account App-Key
    rolesSelector:
      matchLabels:
        testing.upbound.io/example-name: sa_app_key
---

apiVersion: iam.datadog.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/role
  labels:
    testing.upbound.io/example-name: sa_app_key
  name: app-key-example
spec:
  forProvider:
    name: uptest
    permission:
      - id: 4d87d5f8-d8b1-11e9-a77a-eb9c8350d04f
