apiVersion: iam.datadog.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: sa_example
  name: uptest
spec:
  forProvider:
    email: new@example.com
    name: Service Account Uptest
    rolesSelector:
      matchLabels:
        testing.upbound.io/example-name: sa_example
---

apiVersion: iam.datadog.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/role
  labels:
    testing.upbound.io/example-name: sa_example
  name: sa-example
spec:
  forProvider:
    name: uptest
    permission:
      - id: 4d87d5f8-d8b1-11e9-a77a-eb9c8350d04f
