/*
Copyright 2026 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PageInitParameters struct {

	// (String) The company logo displayed on the status page.
	// The company logo displayed on the status page.
	CompanyLogo *string `json:"companyLogo,omitempty" tf:"company_logo,omitempty"`

	// (String) The subdomain prefix used to build the status page's URL.
	// The subdomain prefix used to build the status page's URL.
	DomainPrefix *string `json:"domainPrefix,omitempty" tf:"domain_prefix,omitempty"`

	// (String) The header image included in subscriber emails.
	// The header image included in subscriber emails.
	EmailHeaderImage *string `json:"emailHeaderImage,omitempty" tf:"email_header_image,omitempty"`

	// (String) The favicon displayed for the status page.
	// The favicon displayed for the status page.
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The icon used for the status page's Slack app integration.
	// The icon used for the status page's Slack app integration.
	SlackAppIcon *string `json:"slackAppIcon,omitempty" tf:"slack_app_icon,omitempty"`

	// (Boolean) Whether Slack subscriber notifications are enabled for the status page.
	// Whether Slack subscriber notifications are enabled for the status page.
	SlackSubscriptionsEnabled *bool `json:"slackSubscriptionsEnabled,omitempty" tf:"slack_subscriptions_enabled,omitempty"`

	// (Boolean) Whether subscriber notifications are enabled for the status page.
	// Whether subscriber notifications are enabled for the status page.
	SubscriptionsEnabled *bool `json:"subscriptionsEnabled,omitempty" tf:"subscriptions_enabled,omitempty"`

	// (String) The type of the status page. Valid values are: public, internal.
	// The type of the status page. Valid values are: public, internal.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	// How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	VisualizationType *string `json:"visualizationType,omitempty" tf:"visualization_type,omitempty"`
}

type PageObservation struct {

	// (String) The company logo displayed on the status page.
	// The company logo displayed on the status page.
	CompanyLogo *string `json:"companyLogo,omitempty" tf:"company_logo,omitempty"`

	// (String) Timestamp when the status page was created.
	// Timestamp when the status page was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// domain flow, not by this resource.
	// The custom domain configured for the status page, if any. Managed through a separate custom-domain flow, not by this resource.
	CustomDomain *string `json:"customDomain,omitempty" tf:"custom_domain,omitempty"`

	// domain flow, not by this resource.
	// Whether the custom domain is enabled for the status page. Managed through a separate custom-domain flow, not by this resource.
	CustomDomainEnabled *bool `json:"customDomainEnabled,omitempty" tf:"custom_domain_enabled,omitempty"`

	// (String) The subdomain prefix used to build the status page's URL.
	// The subdomain prefix used to build the status page's URL.
	DomainPrefix *string `json:"domainPrefix,omitempty" tf:"domain_prefix,omitempty"`

	// (String) The header image included in subscriber emails.
	// The header image included in subscriber emails.
	EmailHeaderImage *string `json:"emailHeaderImage,omitempty" tf:"email_header_image,omitempty"`

	// (Boolean) Whether the status page is published. Managed by the publish/unpublish API operations, not by this resource; always reflects the page's current state.
	// Whether the status page is published. Managed by the publish/unpublish API operations, not by this resource; always reflects the page's current state.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The favicon displayed for the status page.
	// The favicon displayed for the status page.
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) The ID of the status page.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Timestamp when the status page was last modified.
	// Timestamp when the status page was last modified.
	ModifiedAt *string `json:"modifiedAt,omitempty" tf:"modified_at,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL of the status page.
	// The URL of the status page.
	PageURL *string `json:"pageUrl,omitempty" tf:"page_url,omitempty"`

	// (String) The icon used for the status page's Slack app integration.
	// The icon used for the status page's Slack app integration.
	SlackAppIcon *string `json:"slackAppIcon,omitempty" tf:"slack_app_icon,omitempty"`

	// (Boolean) Whether Slack subscriber notifications are enabled for the status page.
	// Whether Slack subscriber notifications are enabled for the status page.
	SlackSubscriptionsEnabled *bool `json:"slackSubscriptionsEnabled,omitempty" tf:"slack_subscriptions_enabled,omitempty"`

	// (Boolean) Whether subscriber notifications are enabled for the status page.
	// Whether subscriber notifications are enabled for the status page.
	SubscriptionsEnabled *bool `json:"subscriptionsEnabled,omitempty" tf:"subscriptions_enabled,omitempty"`

	// (String) The type of the status page. Valid values are: public, internal.
	// The type of the status page. Valid values are: public, internal.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	// How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	VisualizationType *string `json:"visualizationType,omitempty" tf:"visualization_type,omitempty"`
}

type PageParameters struct {

	// (String) The company logo displayed on the status page.
	// The company logo displayed on the status page.
	// +kubebuilder:validation:Optional
	CompanyLogo *string `json:"companyLogo,omitempty" tf:"company_logo,omitempty"`

	// (String) The subdomain prefix used to build the status page's URL.
	// The subdomain prefix used to build the status page's URL.
	// +kubebuilder:validation:Optional
	DomainPrefix *string `json:"domainPrefix,omitempty" tf:"domain_prefix,omitempty"`

	// (String) The header image included in subscriber emails.
	// The header image included in subscriber emails.
	// +kubebuilder:validation:Optional
	EmailHeaderImage *string `json:"emailHeaderImage,omitempty" tf:"email_header_image,omitempty"`

	// (String) The favicon displayed for the status page.
	// The favicon displayed for the status page.
	// +kubebuilder:validation:Optional
	Favicon *string `json:"favicon,omitempty" tf:"favicon,omitempty"`

	// (String) The name of the status page.
	// The name of the status page.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The icon used for the status page's Slack app integration.
	// The icon used for the status page's Slack app integration.
	// +kubebuilder:validation:Optional
	SlackAppIcon *string `json:"slackAppIcon,omitempty" tf:"slack_app_icon,omitempty"`

	// (Boolean) Whether Slack subscriber notifications are enabled for the status page.
	// Whether Slack subscriber notifications are enabled for the status page.
	// +kubebuilder:validation:Optional
	SlackSubscriptionsEnabled *bool `json:"slackSubscriptionsEnabled,omitempty" tf:"slack_subscriptions_enabled,omitempty"`

	// (Boolean) Whether subscriber notifications are enabled for the status page.
	// Whether subscriber notifications are enabled for the status page.
	// +kubebuilder:validation:Optional
	SubscriptionsEnabled *bool `json:"subscriptionsEnabled,omitempty" tf:"subscriptions_enabled,omitempty"`

	// (String) The type of the status page. Valid values are: public, internal.
	// The type of the status page. Valid values are: public, internal.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	// How component statuses are visualized on the page. Valid values are: bars_and_uptime_percentage, bars_only, component_name_only.
	// +kubebuilder:validation:Optional
	VisualizationType *string `json:"visualizationType,omitempty" tf:"visualization_type,omitempty"`
}

// PageSpec defines the desired state of Page
type PageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PageInitParameters `json:"initProvider,omitempty"`
}

// PageStatus defines the observed state of Page.
type PageStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Page is the Schema for the Pages API. Provides a Datadog status page resource. This can be used to create and manage Datadog status pages.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,datadog}
type Page struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domainPrefix) || (has(self.initProvider) && has(self.initProvider.domainPrefix))",message="spec.forProvider.domainPrefix is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.visualizationType) || (has(self.initProvider) && has(self.initProvider.visualizationType))",message="spec.forProvider.visualizationType is a required parameter"
	Spec   PageSpec   `json:"spec"`
	Status PageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PageList contains a list of Pages
type PageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Page `json:"items"`
}

// Repository type metadata.
var (
	Page_Kind             = "Page"
	Page_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Page_Kind}.String()
	Page_KindAPIVersion   = Page_Kind + "." + CRDGroupVersion.String()
	Page_GroupVersionKind = CRDGroupVersion.WithKind(Page_Kind)
)

func init() {
	SchemeBuilder.Register(&Page{}, &PageList{})
}
