apiVersion: integration.datadog.m.upbound.io/v1alpha1
kind: AWSAccountCCMConfig
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/awsaccountccmconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    awsAccountConfigIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ccmConfig:
    - dataExportConfigs:
      - bucketName: billing
        bucketRegion: us-east-1
        reportName: cost-and-usage-report
        reportPrefix: reports
        reportType: CUR2.0
