apiVersion: apm.datadog.m.upbound.io/v1alpha1
kind: RetentionFilterOrder
metadata:
  annotations:
    meta.upbound.io/example-id: apm/v1alpha1/retentionfilterorder
    upjet.upbound.io/manual-intervention: The API requires the complete ordered list of the organization's retention filters; replace the list with all retention filters of the organization.
  labels:
    testing.upbound.io/example-name: bar
  name: bar
  namespace: upbound-system
spec:
  forProvider:
    filterIdsRefs:
    - name: retentionfilterorder-foo

---

apiVersion: apm.datadog.m.upbound.io/v1alpha1
kind: RetentionFilter
metadata:
  annotations:
    meta.upbound.io/example-id: apm.datadog/v1alpha1/retentionfilterorder
  labels:
    testing.upbound.io/example-name: retentionfilterorder-foo
  name: retentionfilterorder-foo
  namespace: crossplane-system
spec:
  forProvider:
    enabled: false
    filter:
      query: '*'
    filterType: spans-sampling-processor
    name: Sample order
    rate: "1.0"
