name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    uses: upbound/uptest/.github/workflows/provider-tag.yml@8965579a213ba2b249225fa311178ac66f107daf # main
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
