apiVersion: datastore.upbound.io/v1alpha1
kind: Item
metadata:
  annotations:
    meta.upbound.io/example-id: datastore/v1alpha1/item
  labels:
    testing.upbound.io/example-name: user1
  name: user1
spec:
  forProvider:
    datastoreId: ${datadog_datastore.example.id}
    itemKey: user-123
    value:
      email: john@example.com
      id: user-123
      status: active
      username: john_doe

---

apiVersion: datadog.upbound.io/v1alpha1
kind: Datastore
metadata:
  annotations:
    meta.upbound.io/example-id: datastore/v1alpha1/item
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Datastore for user data
    name: users-datastore
    primaryColumnName: id
    primaryKeyGenerationStrategy: none
